### PR TITLE
Add docker container and lua script for feeding data to Prometheus push gateway

### PR DESCRIPTION
**Pull request by t-lo**
# Prometheus push gateway support for wrk2 

This PR adds support for exporting data to a Prometheus push gateway. Both run-time data (during benchmark execution) as well as result data (latency histogram) will be exported.
The PR adds a LUA script, a wrk2 wrapper script (shell), and a build recipe for a docker container image.

# How to use

For testing the PR it is recommended to build and run the benchmark container on the local developer machine, testing against a local HTTP endpoint, and feeding the benchmark data to a Prometheus push gateway in a kubernetes cluster.

Instructions below assume 
1. a kubernetes cluster is available with 
  1.a Prometheus
  1.b push gateway
  1.c and Grafana installed and set up
2. A HTTP endpoint available on the local host for testing

Steps to use:
1. Build the docker container
```shell
$ docker docker build -t wrk2-prometheus -f docker/Dockerfile.benchmark-container-prometheus-export .
```
2. Create suitable port forwards to the push gateway and to Grafana, using the namespace and service names that match your cluster's. The below commands assume we use a `monitoring` namespace and [Lokomotive's Prometheus oerator](https://github.com/kinvolk/lokomotive/tree/master/assets/components/prometheus-operator/manifests): 
```shell
$ kubectl -n monitoring port-forward svc/prometheus-operator-grafana 3000:80 &
$ kubectl -n monitoring port-forward svc/pushgateway 9091 &
```
3. import the experimental [wrk2 cockpit dashboard](https://github.com/kinvolk/service-mesh-benchmark/pull/16) to Grafana. Open the imported dashboard. Set the time span (upper right hand side) to "last 5 minutes", and the refresh rate to "1s" or "5s".
image (1)

4. Run the benchmark container on your local machine. It will use the push gateway port forwarded in step 2. to push metrics. In the below example the local machine provides a HTTP endpoint at `http://127.0.0.1/index.txt`. We'll run a test with 10 simultaneous connections and 1000 RPS for 60 seconds:
```shell
$ docker run --net=host -ti wrk2-prometheus -p http://127.0.0.1:9091/metrics/job/wrk2_bench_test/instance/test_run -c 10 -d 60 -r 1000 http://127.0.0.1/index.txt
```

# Testing done

Ran the above for 60, 300, and 600 seconds, with 1000, 5000, and 10000 RPS, and 10, 50, 200 parallel connections on my local machine.

### CODE REVIEW

**Comment by surajssd** [comment]
@t-lo The app always stops with non-zero exit code but what the error is, is not very visible:

```bash
...
  59997 requests in 1.00m, 48.63MB read
Requests/sec:   1000.30
Transfer/sec:    830.27KB
Total Requests: 59997
HTTP errors: 0
Requests timed out: 0
Bytes received: 50994470
Socket connect errors: 0
Socket read errors: 0
Socket write errors: 0

URL call count
http://127.0.0.1 : 60010


$ echo $?
56
```

**Comment by t-lo** [comment]
Hmmm, I suspect the Prometheus push gateway is unreachable from where you're running the test. The container should validate the push gateway before starting the benchmark - I've just added this.

Can you please re-test? Also, you may use the `-p stdout` command line option to just print prometheus metrics to stdout.

**Comment by t-lo** [comment]
ping @surajssd

**Review by surajssd — APPROVED** [review]
I tried the given instructions and now I don't see the non-zero exit code.

**Pull request merged**
